'use strict';

// This file is auto-generated

// prettier-ignore
module.exports = {
  'android': {
    '4.4': {
      'amazon kindle fire hd 8.9 emulator': {'browserName': 'Browser', 'deviceName': 'Amazon Kindle Fire HD 8.9 Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
      'android emulator': {'browserName': 'Browser', 'deviceName': 'Android Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
      'google nexus 7 hd emulator': {'browserName': 'Browser', 'deviceName': 'Google Nexus 7 HD Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
      'google nexus 7c emulator': {'browserName': 'Browser', 'deviceName': 'Google Nexus 7C Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
      'lg nexus 4 emulator': {'browserName': 'Browser', 'deviceName': 'LG Nexus 4 Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
      'samsung galaxy nexus emulator': {'browserName': 'Browser', 'deviceName': 'Samsung Galaxy Nexus Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
      'samsung galaxy s3 emulator': {'browserName': 'Browser', 'deviceName': 'Samsung Galaxy S3 Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
      'samsung galaxy s4 emulator': {'browserName': 'Browser', 'deviceName': 'Samsung Galaxy S4 Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '4.4'},
    },
    '5.0': {
      'android emulator': {'browserName': 'Browser', 'deviceName': 'Android Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '5.0'},
    },
    '5.1': {
      'android emulator': {'browserName': 'Browser', 'deviceName': 'Android Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '5.1'},
    },
    '6.0': {
      'android emulator': {'browserName': 'Chrome', 'deviceName': 'Android Emulator', 'deviceOrientation': 'portrait', 'platformName': 'Android', 'platformVersion': '6.0'},
    },
  },
  'chrome': {
    '26': {
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '26.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '26.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '26.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '26.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '26.0'},
    },
    '27': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '27.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '27.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '27.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '27.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '27.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '27.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '27.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '27.0'},
    },
    '28': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '28.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '28.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '28.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '28.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '28.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '28.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '28.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '28.0'},
    },
    '29': {
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '29.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '29.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '29.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '29.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '29.0'},
    },
    '30': {
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '30.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '30.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '30.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '30.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '30.0'},
    },
    '31': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '31.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '31.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '31.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '31.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '31.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '31.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '31.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '31.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '31.0'},
    },
    '32': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '32.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '32.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '32.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '32.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '32.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '32.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '32.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '32.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '32.0'},
    },
    '33': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '33.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '33.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '33.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '33.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '33.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '33.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '33.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '33.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '33.0'},
    },
    '34': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '34.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '34.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '34.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '34.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '34.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '34.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '34.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '34.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '34.0'},
    },
    '35': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '35.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '35.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '35.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '35.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '35.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '35.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '35.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '35.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '35.0'},
    },
    '36': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '36.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '36.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '36.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '36.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '36.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '36.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '36.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '36.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '36.0'},
    },
    '37': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '37.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '37.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '37.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '37.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '37.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '37.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '37.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '37.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '37.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '37.0'},
    },
    '38': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '38.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '38.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '38.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '38.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '38.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '38.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '38.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '38.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '38.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '38.0'},
    },
    '39': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '39.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '39.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '39.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '39.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '39.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '39.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '39.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '39.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '39.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '39.0'},
    },
    '40': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '40.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '40.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '40.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '40.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '40.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '40.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '40.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '40.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '40.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '40.0'},
    },
    '41': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '41.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '41.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '41.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '41.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '41.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '41.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '41.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '41.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '41.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '41.0'},
    },
    '42': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '42.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '42.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '42.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '42.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '42.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '42.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '42.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '42.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '42.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '42.0'},
    },
    '43': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '43.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '43.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '43.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '43.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '43.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '43.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '43.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '43.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '43.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '43.0'},
    },
    '44': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '44.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '44.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '44.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '44.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '44.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '44.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '44.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '44.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '44.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '44.0'},
    },
    '45': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '45.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '45.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '45.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '45.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '45.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '45.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '45.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '45.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '45.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '45.0'},
    },
    '46': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '46.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '46.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '46.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '46.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '46.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '46.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '46.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '46.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '46.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '46.0'},
    },
    '47': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '47.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '47.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '47.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '47.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '47.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '47.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '47.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '47.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '47.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '47.0'},
    },
    '48': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '48.0'},
      'linux': {'browserName': 'chrome', 'platform': 'Linux', 'version': '48.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '48.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '48.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '48.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '48.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '48.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '48.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '48.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '48.0'},
    },
    '49': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '49.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '49.0'},
      'mountain_lion': {'browserName': 'chrome', 'platform': 'OS X 10.8', 'version': '49.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '49.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '49.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '49.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '49.0'},
      'xp': {'browserName': 'chrome', 'platform': 'Windows XP', 'version': '49.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '49.0'},
    },
    '50': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '50.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '50.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '50.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '50.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '50.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '50.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '50.0'},
    },
    '51': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '51.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '51.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '51.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '51.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '51.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '51.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '51.0'},
    },
    '52': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '52.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '52.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '52.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '52.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '52.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '52.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '52.0'},
    },
    '53': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '53.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '53.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '53.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '53.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '53.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '53.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '53.0'},
    },
    '54': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '54.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '54.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '54.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '54.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '54.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '54.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '54.0'},
    },
    '55': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '55.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '55.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '55.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '55.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '55.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '55.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '55.0'},
    },
    '56': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '56.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '56.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '56.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '56.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '56.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '56.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '56.0'},
    },
    '57': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '57.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '57.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '57.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '57.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '57.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '57.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '57.0'},
    },
    '58': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': '58.0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': '58.0'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': '58.0'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': '58.0'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': '58.0'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': '58.0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': '58.0'},
    },
    'beta': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': 'beta'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': 'beta'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': 'beta'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': 'beta'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': 'beta'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': 'beta'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': 'beta'},
    },
    'dev': {
      'capitan': {'browserName': 'chrome', 'platform': 'OS X 10.11', 'version': 'dev'},
      'mavericks': {'browserName': 'chrome', 'platform': 'OS X 10.9', 'version': 'dev'},
      'sierra': {'browserName': 'chrome', 'platform': 'macOS 10.12', 'version': 'dev'},
      'win10': {'browserName': 'chrome', 'platform': 'Windows 10', 'version': 'dev'},
      'win7': {'browserName': 'chrome', 'platform': 'Windows 7', 'version': 'dev'},
      'win8': {'browserName': 'chrome', 'platform': 'Windows 8.1', 'version': 'dev'},
      'yosemite': {'browserName': 'chrome', 'platform': 'OS X 10.10', 'version': 'dev'},
    },
  },
  'edge': {
    '13': {
      'win10': {'browserName': 'MicrosoftEdge', 'platform': 'Windows 10', 'version': '13.10586.'},
    },
    '14': {
      'win10': {'browserName': 'MicrosoftEdge', 'platform': 'Windows 10', 'version': '14.14393.'},
    },
  },
  'firefox': {
    '10': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '10.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '10.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '10.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '10.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '10.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '10.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '10.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '10.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '10.0'},
    },
    '11': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '11.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '11.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '11.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '11.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '11.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '11.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '11.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '11.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '11.0'},
    },
    '12': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '12.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '12.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '12.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '12.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '12.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '12.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '12.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '12.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '12.0'},
    },
    '13': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '13.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '13.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '13.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '13.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '13.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '13.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '13.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '13.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '13.0'},
    },
    '14': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '14.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '14.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '14.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '14.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '14.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '14.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '14.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '14.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '14.0'},
    },
    '15': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '15.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '15.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '15.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '15.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '15.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '15.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '15.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '15.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '15.0'},
    },
    '16': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '16.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '16.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '16.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '16.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '16.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '16.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '16.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '16.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '16.0'},
    },
    '17': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '17.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '17.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '17.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '17.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '17.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '17.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '17.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '17.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '17.0'},
    },
    '18': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '18.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '18.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '18.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '18.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '18.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '18.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '18.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '18.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '18.0'},
    },
    '19': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '19.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '19.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '19.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '19.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '19.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '19.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '19.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '19.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '19.0'},
    },
    '20': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '20.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '20.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '20.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '20.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '20.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '20.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '20.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '20.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '20.0'},
    },
    '21': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '21.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '21.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '21.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '21.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '21.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '21.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '21.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '21.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '21.0'},
    },
    '22': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '22.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '22.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '22.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '22.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '22.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '22.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '22.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '22.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '22.0'},
    },
    '23': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '23.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '23.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '23.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '23.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '23.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '23.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '23.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '23.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '23.0'},
    },
    '24': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '24.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '24.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '24.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '24.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '24.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '24.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '24.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '24.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '24.0'},
    },
    '25': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '25.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '25.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '25.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '25.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '25.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '25.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '25.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '25.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '25.0'},
    },
    '26': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '26.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '26.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '26.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '26.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '26.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '26.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '26.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '26.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '26.0'},
    },
    '27': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '27.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '27.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '27.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '27.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '27.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '27.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '27.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '27.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '27.0'},
    },
    '28': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '28.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '28.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '28.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '28.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '28.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '28.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '28.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '28.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '28.0'},
    },
    '29': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '29.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '29.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '29.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '29.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '29.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '29.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '29.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '29.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '29.0'},
    },
    '30': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '30.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '30.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '30.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '30.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '30.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '30.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '30.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '30.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '30.0'},
    },
    '31': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '31.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '31.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '31.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '31.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '31.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '31.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '31.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '31.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '31.0'},
    },
    '32': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '32.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '32.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '32.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '32.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '32.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '32.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '32.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '32.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '32.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '32.0'},
    },
    '33': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '33.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '33.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '33.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '33.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '33.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '33.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '33.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '33.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '33.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '33.0'},
    },
    '34': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '34.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '34.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '34.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '34.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '34.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '34.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '34.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '34.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '34.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '34.0'},
    },
    '35': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '35.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '35.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '35.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '35.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '35.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '35.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '35.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '35.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '35.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '35.0'},
    },
    '36': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '36.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '36.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '36.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '36.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '36.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '36.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '36.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '36.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '36.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '36.0'},
    },
    '37': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '37.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '37.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '37.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '37.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '37.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '37.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '37.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '37.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '37.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '37.0'},
    },
    '38': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '38.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '38.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '38.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '38.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '38.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '38.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '38.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '38.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '38.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '38.0'},
    },
    '39': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '39.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '39.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '39.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '39.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '39.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '39.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '39.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '39.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '39.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '39.0'},
    },
    '4': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '4.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '4.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '4.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '4.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '4.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '4.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '4.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '4.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '4.0'},
    },
    '40': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '40.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '40.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '40.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '40.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '40.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '40.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '40.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '40.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '40.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '40.0'},
    },
    '41': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '41.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '41.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '41.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '41.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '41.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '41.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '41.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '41.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '41.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '41.0'},
    },
    '42': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '42.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '42.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '42.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '42.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '42.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '42.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '42.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '42.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '42.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '42.0'},
    },
    '43': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '43.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '43.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '43.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '43.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '43.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '43.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '43.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '43.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '43.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '43.0'},
    },
    '44': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '44.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '44.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '44.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '44.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '44.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '44.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '44.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '44.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '44.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '44.0'},
    },
    '45': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '45.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '45.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '45.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '45.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '45.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '45.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '45.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '45.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '45.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '45.0'},
    },
    '46': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '46.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '46.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '46.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '46.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '46.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '46.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '46.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '46.0'},
    },
    '47': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '47.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '47.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '47.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '47.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '47.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '47.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '47.0'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': '47.0'},
    },
    '48': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '48.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '48.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '48.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '48.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '48.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '48.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '48.0'},
    },
    '49': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '49.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '49.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '49.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '49.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '49.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '49.0'},
    },
    '5': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '5.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '5.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '5.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '5.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '5.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '5.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '5.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '5.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '5.0'},
    },
    '50': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '50.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '50.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '50.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '50.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '50.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '50.0'},
    },
    '51': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '51.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '51.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '51.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '51.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '51.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '51.0'},
    },
    '52': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '52.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '52.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '52.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '52.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '52.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '52.0'},
    },
    '53': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '53.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '53.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '53.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '53.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '53.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '53.0'},
    },
    '6': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '6.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '6.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '6.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '6.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '6.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '6.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '6.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '6.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '6.0'},
    },
    '7': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '7.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '7.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '7.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '7.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '7.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '7.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '7.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '7.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '7.0'},
    },
    '8': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '8.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '8.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '8.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '8.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '8.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '8.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '8.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '8.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '8.0'},
    },
    '9': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': '9.0'},
      'linux': {'browserName': 'firefox', 'platform': 'Linux', 'version': '9.0'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': '9.0'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': '9.0'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': '9.0'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': '9.0'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': '9.0'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': '9.0'},
      'xp': {'browserName': 'firefox', 'platform': 'Windows XP', 'version': '9.0'},
    },
    'beta': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': 'beta'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': 'beta'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': 'beta'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': 'beta'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': 'beta'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': 'beta'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': 'beta'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': 'beta'},
    },
    'dev': {
      'capitan': {'browserName': 'firefox', 'platform': 'OS X 10.11', 'version': 'dev'},
      'mavericks': {'browserName': 'firefox', 'platform': 'OS X 10.9', 'version': 'dev'},
      'mountain_lion': {'browserName': 'firefox', 'platform': 'OS X 10.8', 'version': 'dev'},
      'sierra': {'browserName': 'firefox', 'platform': 'macOS 10.12', 'version': 'dev'},
      'win10': {'browserName': 'firefox', 'platform': 'Windows 10', 'version': 'dev'},
      'win7': {'browserName': 'firefox', 'platform': 'Windows 7', 'version': 'dev'},
      'win8': {'browserName': 'firefox', 'platform': 'Windows 8.1', 'version': 'dev'},
      'yosemite': {'browserName': 'firefox', 'platform': 'OS X 10.10', 'version': 'dev'},
    },
  },
  'ie': {
    '10': {
      'win7': {'browserName': 'internet explorer', 'platform': 'Windows 7', 'version': '10.0'},
      'win8': {'browserName': 'internet explorer', 'platform': 'Windows 8', 'version': '10.0'},
    },
    '11': {
      'win10': {'browserName': 'internet explorer', 'platform': 'Windows 10', 'version': '11.103'},
      'win7': {'browserName': 'internet explorer', 'platform': 'Windows 7', 'version': '11.0'},
      'win8': {'browserName': 'internet explorer', 'platform': 'Windows 8.1', 'version': '11.0'},
    },
    '6': {
      'xp': {'browserName': 'internet explorer', 'platform': 'Windows XP', 'version': '6.0'},
    },
    '7': {
      'xp': {'browserName': 'internet explorer', 'platform': 'Windows XP', 'version': '7.0'},
    },
    '8': {
      'win7': {'browserName': 'internet explorer', 'platform': 'Windows 7', 'version': '8.0'},
      'xp': {'browserName': 'internet explorer', 'platform': 'Windows XP', 'version': '8.0'},
    },
    '9': {
      'win7': {'browserName': 'internet explorer', 'platform': 'Windows 7', 'version': '9.0'},
    },
  },
  'ios': {
    '10.0': {
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'ipad air 2': {'browserName': 'Safari', 'deviceName': 'iPad Air 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'ipad pro (12.9-inch)': {'browserName': 'Safari', 'deviceName': 'iPad Pro (12.9 inch) Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'ipad pro (9.7-inch)': {'browserName': 'Safari', 'deviceName': 'iPad Pro (9.7 inch) Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 6s': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 6s plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 7': {'browserName': 'Safari', 'deviceName': 'iPhone 7 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone 7 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 7 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone se': {'browserName': 'Safari', 'deviceName': 'iPhone SE Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.0'},
    },
    '10.2': {
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'ipad air 2': {'browserName': 'Safari', 'deviceName': 'iPad Air 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'ipad pro (12.9-inch)': {'browserName': 'Safari', 'deviceName': 'iPad Pro (12.9 inch) Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'ipad pro (9.7-inch)': {'browserName': 'Safari', 'deviceName': 'iPad Pro (9.7 inch) Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 6s': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 6s plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 7': {'browserName': 'Safari', 'deviceName': 'iPhone 7 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone 7 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 7 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone se': {'browserName': 'Safari', 'deviceName': 'iPhone SE Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.2'},
    },
    '10.3': {
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'ipad air 2': {'browserName': 'Safari', 'deviceName': 'iPad Air 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'ipad pro (12.9-inch)': {'browserName': 'Safari', 'deviceName': 'iPad Pro (12.9 inch) Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'ipad pro (9.7-inch)': {'browserName': 'Safari', 'deviceName': 'iPad Pro (9.7 inch) Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 6s': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 6s plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 7': {'browserName': 'Safari', 'deviceName': 'iPhone 7 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone 7 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 7 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone se': {'browserName': 'Safari', 'deviceName': 'iPhone SE Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '10.3'},
    },
    '8.1': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.1'},
    },
    '8.2': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.2'},
    },
    '8.3': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.3'},
    },
    '8.4': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '8.4'},
    },
    '9.0': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'ipad air 2': {'browserName': 'Safari', 'deviceName': 'iPad Air 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone 6s': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone 6s plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.0'},
    },
    '9.1': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'ipad air 2': {'browserName': 'Safari', 'deviceName': 'iPad Air 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'ipad pro': {'browserName': 'Safari', 'deviceName': 'iPad Pro Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone 6s': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone 6s plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.1'},
    },
    '9.2': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'ipad air 2': {'browserName': 'Safari', 'deviceName': 'iPad Air 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'ipad pro': {'browserName': 'Safari', 'deviceName': 'iPad Pro Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.2'},
    },
    '9.3': {
      'ipad 2': {'browserName': 'Safari', 'deviceName': 'iPad 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'ipad air': {'browserName': 'Safari', 'deviceName': 'iPad Air Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'ipad air 2': {'browserName': 'Safari', 'deviceName': 'iPad Air 2 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'ipad pro': {'browserName': 'Safari', 'deviceName': 'iPad Pro Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'ipad retina': {'browserName': 'Safari', 'deviceName': 'iPad Retina Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'ipad simulator': {'browserName': 'Safari', 'deviceName': 'iPad Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone 4s': {'browserName': 'Safari', 'deviceName': 'iPhone 4s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone 5': {'browserName': 'Safari', 'deviceName': 'iPhone 5 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone 5s': {'browserName': 'Safari', 'deviceName': 'iPhone 5s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone 6': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone 6 plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6 Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone 6s': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone 6s plus': {'browserName': 'Safari', 'deviceName': 'iPhone 6s Plus Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
      'iphone simulator': {'browserName': 'Safari', 'deviceName': 'iPhone Simulator', 'deviceOrientation': 'portrait', 'platformName': 'iOS', 'platformVersion': '9.3'},
    },
  },
  'opera': {
    '11': {
      'win7': {'browserName': 'opera', 'platform': 'Windows 7', 'version': '11.64'},
      'xp': {'browserName': 'opera', 'platform': 'Windows XP', 'version': '11.64'},
    },
    '12': {
      'linux': {'browserName': 'opera', 'platform': 'Linux', 'version': '12.15'},
      'win7': {'browserName': 'opera', 'platform': 'Windows 7', 'version': '12.12'},
      'xp': {'browserName': 'opera', 'platform': 'Windows XP', 'version': '12.12'},
    },
  },
  'safari': {
    '10': {
      'capitan': {'browserName': 'safari', 'platform': 'OS X 10.11', 'version': '10.0'},
      'sierra': {'browserName': 'safari', 'platform': 'macOS 10.12', 'version': '10.0'},
    },
    '5.1': {
      'win7': {'browserName': 'safari', 'platform': 'Windows 7', 'version': '5.1'},
    },
    '6': {
      'mountain_lion': {'browserName': 'safari', 'platform': 'OS X 10.8', 'version': '6.0'},
    },
    '7': {
      'mavericks': {'browserName': 'safari', 'platform': 'OS X 10.9', 'version': '7.0'},
    },
    '8': {
      'yosemite': {'browserName': 'safari', 'platform': 'OS X 10.10', 'version': '8.0'},
    },
    '9': {
      'capitan': {'browserName': 'safari', 'platform': 'OS X 10.11', 'version': '9.0'},
    },
  },
};
