'use strict';

// This file is auto-generated

// prettier-ignore
module.exports = {
  'android': {
    '4.4': {
      'galaxy nexus': {'browserName': 'browser', 'deviceName': 'Galaxy Nexus', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '4.4'},
      'galaxy s4': {'browserName': 'browser', 'deviceName': 'Galaxy S4', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '4.4'},
    },
    '5.0': {
      'galaxy s5': {'browserName': 'browser', 'deviceName': 'Galaxy S5', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '5.0'},
      'google nexus 1': {'browserName': 'browser', 'deviceName': 'Nexus 1', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '5.0'},
    },
    '6.0': {
      'galaxy s6': {'browserName': 'browser', 'deviceName': 'Galaxy S6', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '6.0'},
      'google nexus 4': {'browserName': 'browser', 'deviceName': 'Nexus 4', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '6.0'},
      'google nexus s': {'browserName': 'browser', 'deviceName': 'Nexus S', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '6.0'},
    },
    '7.1': {
      'google nexus 7': {'browserName': 'Chrome', 'deviceName': 'Nexus 7', 'platform': 'ANDROID', 'platformName': 'Android', 'version': '7.1'},
    },
  },
  'chrome': {
    '0': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '0'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '0'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '0'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '0'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '0'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '0'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '0'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '0'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '0'},
    },
    '36': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '36'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '36'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '36'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '36'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '36'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '36'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '36'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '36'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '36'},
    },
    '37': {
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '37'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '37'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '37'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '37'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '37'},
    },
    '38': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '38'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '38'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '38'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '38'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '38'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '38'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '38'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '38'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '38'},
    },
    '39': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '39'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '39'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '39'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '39'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '39'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '39'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '39'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '39'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '39'},
    },
    '40': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '40'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '40'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '40'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '40'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '40'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '40'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '40'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '40'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '40'},
    },
    '41': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '41'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '41'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '41'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '41'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '41'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '41'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '41'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '41'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '41'},
    },
    '42': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '42'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '42'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '42'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '42'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '42'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '42'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '42'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '42'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '42'},
    },
    '43': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '43'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '43'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '43'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '43'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '43'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '43'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '43'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '43'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '43'},
    },
    '44': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '44'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '44'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '44'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '44'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '44'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '44'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '44'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '44'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '44'},
    },
    '45': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '45'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '45'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '45'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '45'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '45'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '45'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '45'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '45'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '45'},
    },
    '46': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '46'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '46'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '46'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '46'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '46'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '46'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '46'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '46'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '46'},
    },
    '47': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '47'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '47'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '47'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '47'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '47'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '47'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '47'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '47'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '47'},
    },
    '48': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '48'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '48'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '48'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '48'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '48'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '48'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '48'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '48'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '48'},
    },
    '49': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '49'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '49'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '49'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '49'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '49'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '49'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '49'},
      'xp': {'browserName': 'chrome', 'platform': 'XP', 'version': '49'},
    },
    '50': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '50'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '50'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '50'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '50'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '50'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '50'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '50'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '50'},
    },
    '51': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '51'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '51'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '51'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '51'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '51'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '51'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '51'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '51'},
    },
    '52': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '52'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '52'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '52'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '52'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '52'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '52'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '52'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '52'},
    },
    '53': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '53'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '53'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '53'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '53'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '53'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '53'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '53'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '53'},
    },
    '54': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '54'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '54'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '54'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '54'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '54'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '54'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '54'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '54'},
    },
    '55': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '55'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '55'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '55'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '55'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '55'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '55'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '55'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '55'},
    },
    '56': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '56'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '56'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '56'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '56'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '56'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '56'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '56'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '56'},
    },
    '57': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '57'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '57'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '57'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '57'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '57'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '57'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '57'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '57'},
    },
    '58': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '58'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '58'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '58'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '58'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '58'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '58'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '58'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '58'},
    },
    '59': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': '59'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': '59'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': '59'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': '59'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': '59'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': '59'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': '59'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': '59'},
    },
    'beta': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': 'beta'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': 'beta'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': 'beta'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': 'beta'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': 'beta'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': 'beta'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': 'beta'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': 'beta'},
    },
    'dev': {
      'capitan': {'browserName': 'chrome', 'platform': 'CAPITAN', 'version': 'dev'},
      'linux': {'browserName': 'chrome', 'platform': 'LINUX', 'version': 'dev'},
      'mavericks': {'browserName': 'chrome', 'platform': 'MAVERICKS', 'version': 'dev'},
      'sierra': {'browserName': 'chrome', 'platform': 'SIERRA', 'version': 'dev'},
      'vista': {'browserName': 'chrome', 'platform': 'VISTA', 'version': 'dev'},
      'win10': {'browserName': 'chrome', 'platform': 'WIN10', 'version': 'dev'},
      'win8': {'browserName': 'chrome', 'platform': 'WIN8', 'version': 'dev'},
      'yosemite': {'browserName': 'chrome', 'platform': 'YOSEMITE', 'version': 'dev'},
    },
  },
  'edge': {
    '13': {
      'win10': {'browserName': 'microsoftedge', 'platform': 'WIN10', 'version': '13'},
    },
    '14': {
      'win10': {'browserName': 'microsoftedge', 'platform': 'WIN10', 'version': '14'},
    },
  },
  'firefox': {
    '10': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '10'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '10'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '10'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '10'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '10'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '10'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '10'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '10'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '10'},
    },
    '11': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '11'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '11'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '11'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '11'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '11'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '11'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '11'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '11'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '11'},
    },
    '12': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '12'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '12'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '12'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '12'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '12'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '12'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '12'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '12'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '12'},
    },
    '13': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '13'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '13'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '13'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '13'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '13'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '13'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '13'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '13'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '13'},
    },
    '14': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '14'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '14'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '14'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '14'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '14'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '14'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '14'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '14'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '14'},
    },
    '15': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '15'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '15'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '15'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '15'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '15'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '15'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '15'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '15'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '15'},
    },
    '16': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '16'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '16'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '16'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '16'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '16'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '16'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '16'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '16'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '16'},
    },
    '17': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '17'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '17'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '17'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '17'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '17'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '17'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '17'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '17'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '17'},
    },
    '18': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '18'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '18'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '18'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '18'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '18'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '18'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '18'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '18'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '18'},
    },
    '19': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '19'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '19'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '19'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '19'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '19'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '19'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '19'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '19'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '19'},
    },
    '20': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '20'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '20'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '20'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '20'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '20'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '20'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '20'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '20'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '20'},
    },
    '21': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '21'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '21'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '21'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '21'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '21'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '21'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '21'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '21'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '21'},
    },
    '22': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '22'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '22'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '22'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '22'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '22'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '22'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '22'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '22'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '22'},
    },
    '23': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '23'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '23'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '23'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '23'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '23'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '23'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '23'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '23'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '23'},
    },
    '24': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '24'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '24'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '24'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '24'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '24'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '24'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '24'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '24'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '24'},
    },
    '25': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '25'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '25'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '25'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '25'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '25'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '25'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '25'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '25'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '25'},
    },
    '26': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '26'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '26'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '26'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '26'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '26'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '26'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '26'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '26'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '26'},
    },
    '27': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '27'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '27'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '27'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '27'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '27'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '27'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '27'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '27'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '27'},
    },
    '28': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '28'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '28'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '28'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '28'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '28'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '28'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '28'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '28'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '28'},
    },
    '29': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '29'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '29'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '29'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '29'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '29'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '29'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '29'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '29'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '29'},
    },
    '30': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '30'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '30'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '30'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '30'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '30'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '30'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '30'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '30'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '30'},
    },
    '31': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '31'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '31'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '31'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '31'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '31'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '31'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '31'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '31'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '31'},
    },
    '32': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '32'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '32'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '32'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '32'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '32'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '32'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '32'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '32'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '32'},
    },
    '33': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '33'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '33'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '33'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '33'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '33'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '33'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '33'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '33'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '33'},
    },
    '34': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '34'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '34'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '34'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '34'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '34'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '34'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '34'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '34'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '34'},
    },
    '35': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '35'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '35'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '35'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '35'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '35'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '35'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '35'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '35'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '35'},
    },
    '36': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '36'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '36'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '36'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '36'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '36'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '36'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '36'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '36'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '36'},
    },
    '37': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '37'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '37'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '37'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '37'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '37'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '37'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '37'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '37'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '37'},
    },
    '38': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '38'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '38'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '38'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '38'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '38'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '38'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '38'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '38'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '38'},
    },
    '39': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '39'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '39'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '39'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '39'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '39'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '39'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '39'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '39'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '39'},
    },
    '4': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '4'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '4'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '4'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '4'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '4'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '4'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '4'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '4'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '4'},
    },
    '40': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '40'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '40'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '40'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '40'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '40'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '40'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '40'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '40'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '40'},
    },
    '41': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '41'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '41'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '41'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '41'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '41'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '41'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '41'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '41'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '41'},
    },
    '42': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '42'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '42'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '42'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '42'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '42'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '42'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '42'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '42'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '42'},
    },
    '43': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '43'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '43'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '43'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '43'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '43'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '43'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '43'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '43'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '43'},
    },
    '44': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '44'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '44'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '44'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '44'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '44'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '44'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '44'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '44'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '44'},
    },
    '45': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '45'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '45'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '45'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '45'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '45'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '45'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '45'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '45'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '45'},
    },
    '46': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '46'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '46'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '46'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '46'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '46'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '46'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '46'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '46'},
    },
    '47': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '47'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '47'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '47'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '47'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '47'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '47'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '47'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '47'},
    },
    '48': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '48'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '48'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '48'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '48'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '48'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '48'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '48'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '48'},
    },
    '49': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '49'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '49'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '49'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '49'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '49'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '49'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '49'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '49'},
    },
    '5': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '5'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '5'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '5'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '5'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '5'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '5'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '5'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '5'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '5'},
    },
    '50': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '50'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '50'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '50'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '50'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '50'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '50'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '50'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '50'},
    },
    '51': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '51'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '51'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '51'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '51'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '51'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '51'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '51'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '51'},
    },
    '52': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '52'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '52'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '52'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '52'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '52'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '52'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '52'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '52'},
    },
    '53': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '53'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '53'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '53'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '53'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '53'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '53'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '53'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '53'},
    },
    '6': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '6'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '6'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '6'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '6'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '6'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '6'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '6'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '6'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '6'},
    },
    '7': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '7'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '7'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '7'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '7'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '7'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '7'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '7'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '7'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '7'},
    },
    '8': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '8'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '8'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '8'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '8'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '8'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '8'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '8'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '8'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '8'},
    },
    '9': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': '9'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': '9'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': '9'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': '9'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': '9'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': '9'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': '9'},
      'xp': {'browserName': 'firefox', 'platform': 'XP', 'version': '9'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': '9'},
    },
    'beta': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': 'beta'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': 'beta'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': 'beta'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': 'beta'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': 'beta'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': 'beta'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': 'beta'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': 'beta'},
    },
    'dev': {
      'capitan': {'browserName': 'firefox', 'platform': 'CAPITAN', 'version': 'dev'},
      'linux': {'browserName': 'firefox', 'platform': 'LINUX', 'version': 'dev'},
      'mavericks': {'browserName': 'firefox', 'platform': 'MAVERICKS', 'version': 'dev'},
      'sierra': {'browserName': 'firefox', 'platform': 'SIERRA', 'version': 'dev'},
      'vista': {'browserName': 'firefox', 'platform': 'VISTA', 'version': 'dev'},
      'win10': {'browserName': 'firefox', 'platform': 'WIN10', 'version': 'dev'},
      'win8': {'browserName': 'firefox', 'platform': 'WIN8', 'version': 'dev'},
      'yosemite': {'browserName': 'firefox', 'platform': 'YOSEMITE', 'version': 'dev'},
    },
  },
  'firefox-unbranded': {
    '52': {
      'capitan': {'browserName': 'firefox-unbranded', 'platform': 'CAPITAN', 'version': '52'},
      'linux': {'browserName': 'firefox-unbranded', 'platform': 'LINUX', 'version': '52'},
      'mavericks': {'browserName': 'firefox-unbranded', 'platform': 'MAVERICKS', 'version': '52'},
      'sierra': {'browserName': 'firefox-unbranded', 'platform': 'SIERRA', 'version': '52'},
      'vista': {'browserName': 'firefox-unbranded', 'platform': 'VISTA', 'version': '52'},
      'win10': {'browserName': 'firefox-unbranded', 'platform': 'WIN10', 'version': '52'},
      'win8': {'browserName': 'firefox-unbranded', 'platform': 'WIN8', 'version': '52'},
      'yosemite': {'browserName': 'firefox-unbranded', 'platform': 'YOSEMITE', 'version': '52'},
    },
    '53': {
      'capitan': {'browserName': 'firefox-unbranded', 'platform': 'CAPITAN', 'version': '53'},
      'linux': {'browserName': 'firefox-unbranded', 'platform': 'LINUX', 'version': '53'},
      'mavericks': {'browserName': 'firefox-unbranded', 'platform': 'MAVERICKS', 'version': '53'},
      'sierra': {'browserName': 'firefox-unbranded', 'platform': 'SIERRA', 'version': '53'},
      'vista': {'browserName': 'firefox-unbranded', 'platform': 'VISTA', 'version': '53'},
      'win10': {'browserName': 'firefox-unbranded', 'platform': 'WIN10', 'version': '53'},
      'win8': {'browserName': 'firefox-unbranded', 'platform': 'WIN8', 'version': '53'},
      'yosemite': {'browserName': 'firefox-unbranded', 'platform': 'YOSEMITE', 'version': '53'},
    },
  },
  'ie': {
    '10': {
      'vista': {'browserName': 'internet explorer', 'platform': 'VISTA', 'version': '10'},
      'win8': {'browserName': 'internet explorer', 'platform': 'WIN8', 'version': '10'},
    },
    '11': {
      'vista': {'browserName': 'internet explorer', 'platform': 'VISTA', 'version': '11'},
      'win10': {'browserName': 'internet explorer', 'platform': 'WIN10', 'version': '11'},
      'win8': {'browserName': 'internet explorer', 'platform': 'WIN8', 'version': '11'},
    },
    '6': {
      'xp': {'browserName': 'internet explorer', 'platform': 'XP', 'version': '6'},
    },
    '7': {
      'xp': {'browserName': 'internet explorer', 'platform': 'XP', 'version': '7'},
    },
    '8': {
      'vista': {'browserName': 'internet explorer', 'platform': 'VISTA', 'version': '8'},
    },
    '9': {
      'vista': {'browserName': 'internet explorer', 'platform': 'VISTA', 'version': '9'},
    },
  },
  'ios': {
    '10.3': {
      'ipad 2': {'deviceName': 'iPad 2', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'ipad air': {'deviceName': 'iPad Air', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'ipad air 2': {'deviceName': 'iPad Air 2', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'ipad pro (12.9-inch)': {'deviceName': 'iPad Pro (12.9-inch)', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'ipad retina': {'deviceName': 'iPad Retina', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'iphone 4s': {'deviceName': 'iPhone 4s', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'iphone 5s': {'deviceName': 'iPhone 5s', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'iphone 6': {'deviceName': 'iPhone 6', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'iphone 6 plus': {'deviceName': 'iPhone 6 Plus', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'iphone 6s': {'deviceName': 'iPhone 6s', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
      'iphone 6s plus': {'deviceName': 'iPhone 6s Plus', 'platform': 'SIERRA', 'platformName': 'iOS', 'version': '10.3'},
    },
    '8.1': {
      'iphone 5': {'deviceName': 'iPhone 5', 'platform': 'YOSEMITE', 'platformName': 'iOS', 'version': '8.1'},
      'iphone 5s': {'deviceName': 'iPhone 5s', 'platform': 'YOSEMITE', 'platformName': 'iOS', 'version': '8.1'},
    },
    '9.3': {
      'ipad 2': {'deviceName': 'iPad 2', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'ipad air': {'deviceName': 'iPad Air', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'ipad air 2': {'deviceName': 'iPad Air 2', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'ipad pro': {'deviceName': 'iPad Pro', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'ipad retina': {'deviceName': 'iPad Retina', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'iphone 4s': {'deviceName': 'iPhone 4s', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'iphone 5': {'deviceName': 'iPhone 5', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'iphone 5s': {'deviceName': 'iPhone 5s', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'iphone 6': {'deviceName': 'iPhone 6', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'iphone 6 plus': {'deviceName': 'iPhone 6 Plus', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'iphone 6s': {'deviceName': 'iPhone 6s', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
      'iphone 6s plus': {'deviceName': 'iPhone 6s Plus', 'platform': 'CAPITAN', 'platformName': 'iOS', 'version': '9.3'},
    },
  },
  'opera': {
    '36': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '36'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '36'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '36'},
    },
    '37': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '37'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '37'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '37'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '37'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '37'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '37'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '37'},
    },
    '38': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '38'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '38'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '38'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '38'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '38'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '38'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '38'},
    },
    '39': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '39'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '39'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '39'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '39'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '39'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '39'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': '39'},
    },
    '40': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '40'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '40'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '40'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '40'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '40'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '40'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '40'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': '40'},
    },
    '41': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '41'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '41'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '41'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '41'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '41'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '41'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '41'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': '41'},
    },
    '42': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '42'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '42'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '42'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '42'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '42'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '42'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '42'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': '42'},
    },
    '43': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '43'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '43'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '43'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '43'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '43'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '43'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '43'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': '43'},
    },
    '44': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': '44'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': '44'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': '44'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': '44'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': '44'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': '44'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': '44'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': '44'},
    },
    'beta': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': 'beta'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': 'beta'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': 'beta'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': 'beta'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': 'beta'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': 'beta'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': 'beta'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': 'beta'},
    },
    'dev': {
      'capitan': {'browserName': 'opera', 'platform': 'CAPITAN', 'version': 'dev'},
      'linux': {'browserName': 'opera', 'platform': 'LINUX', 'version': 'dev'},
      'mavericks': {'browserName': 'opera', 'platform': 'MAVERICKS', 'version': 'dev'},
      'sierra': {'browserName': 'opera', 'platform': 'SIERRA', 'version': 'dev'},
      'vista': {'browserName': 'opera', 'platform': 'VISTA', 'version': 'dev'},
      'win10': {'browserName': 'opera', 'platform': 'WIN10', 'version': 'dev'},
      'win8': {'browserName': 'opera', 'platform': 'WIN8', 'version': 'dev'},
      'yosemite': {'browserName': 'opera', 'platform': 'YOSEMITE', 'version': 'dev'},
    },
  },
  'opera_phone': {
    '0': {
      'linux': {'browserName': 'opera_phone', 'platform': 'LINUX', 'version': '0'},
    },
  },
  'opera_tablet': {
    '0': {
      'linux': {'browserName': 'opera_tablet', 'platform': 'LINUX', 'version': '0'},
    },
  },
  'phantomjs': {
    '0': {
      'linux': {'browserName': 'phantomjs', 'platform': 'LINUX', 'version': '0'},
    },
  },
  'safari': {
    '10': {
      'sierra': {'browserName': 'safari', 'platform': 'SIERRA', 'version': '10'},
    },
    '7': {
      'mavericks': {'browserName': 'safari', 'platform': 'MAVERICKS', 'version': '7'},
    },
    '8': {
      'yosemite': {'browserName': 'safari', 'platform': 'YOSEMITE', 'version': '8'},
    },
    '9': {
      'capitan': {'browserName': 'safari', 'platform': 'CAPITAN', 'version': '9'},
    },
    'dev': {
      'capitan': {'browserName': 'safari', 'platform': 'CAPITAN', 'version': 'dev'},
      'sierra': {'browserName': 'safari', 'platform': 'SIERRA', 'version': 'dev'},
    },
  },
};
